name: "Artifacts Challenge"


on: [push]


env: 
    FILE_NAME: output_image.png

jobs:
    create-file:
        name: "Creating Artifacts"
        runs-on: ubuntu-latest

        steps: 
            - name: Checking out the code
              uses: actions/checkout@v1
            - name: Install dependencies 
              run: pip install -r requirements.txt
            - name: Run python file
              run: python artifact_creator.py
            - name: Upload artifacts
              uses: actions/upload-artifact@v1.0.0
              with:
                name: created image
                path: ./${{env.FILE_NAME}}